version: '2'
services:
  kaggle-plant-seedlings-classification:
    image: kaggle-plant-seedling-classification:dev
    container_name: kaggle-plant-seedlings-classification
    volumes:
      - ~/projects/kaggle-plant-seedlings-classification:/kaggle-plant-seedling-classification
      - ~/projects/kaggle_data/plant-seedlings-classification/:/kaggle_data/
      - ~/projects/pre-trained_models/:/pre-trained_models/
    command: 
      - /bin/bash
      - -c
      - sleep infinity

